---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-stocks
  name: go-stocks
spec:
  type: ClusterIP
  ports:
  - name: go-stocks
    port: 8080
    targetPort: 8080
  selector:
    app: go-stocks